services:
  ffc-tcg-customer-registry:
    build:
      context: .
      target: production
    image: ffc-tcg-customer-registry
    container_name: ffc-tcg-customer-registry
    environment:
      APPINSIGHTS_CLOUDROLE: ffc-tcg-customer-registry-local
      APPINSIGHTS_CONNECTIONSTRING: ${APPINSIGHTS_CONNECTIONSTRING}
