services:
  tcg-customer-registry:
    build:
      context: .
      target: production
    image: tcg-customer-registry
    container_name: tcg-customer-registry
    environment:
      APPINSIGHTS_CLOUDROLE: tcg-customer-registry-local
      APPINSIGHTS_CONNECTIONSTRING: ${APPINSIGHTS_CONNECTIONSTRING}
