# This override file should be used when running this service in isolation
# to provide dependencies and expose ports for local testing

services:
  ffc-tcg-customer-registry:
    build:
      target: development
    image: ffc-tcg-customer-registry-development
    container_name: ffc-tcg-customer-registry-development
    ports:
      - "3053:3053"
      - "9253:9229"
    volumes:
      - ./app:/home/node/app
      - ./package.json:/home/node/package.json
