{{- include "ffc-helm-library.container-secret" (list . "tcg-customer-registry.container-secret") -}}
{{- define "tcg-customer-registry.container-secret" -}}
stringData:
  {{- if .Values.appInsights.connectionString }}
  APPINSIGHTS_CONNECTIONSTRING: {{ quote .Values.appInsights.connectionString }}
  {{- end }}
{{- end -}}
