environment: production
environmentCode:
name: ffc-tcg-customer-registry
namespace: tcg-customer
workstream: tcg-customer
image: ffc-tcg-customer-registry

labels:
  component: service

appInsights:
  connectionString:

containerConfigMap:
  name: ffc-tcg-customer-registry-config-map

containerSecret:
  name: ffc-tcg-customer-registry-container-secret
  type: Opaque

deployment: {}

container:
  requestMemory: 100Mi
  requestCpu: 100m
  limitMemory: 100Mi
  limitCpu: 100m
  port: 3053

livenessProbe:
  path: /healthz
  port: 3053
  initialDelaySeconds: 20
  periodSeconds: 10
  failureThreshold: 3
  timeoutSeconds: 5

readinessProbe:
  path: /healthy
  port: 3053
  initialDelaySeconds: 30
  periodSeconds: 10
  failureThreshold: 3
  timeoutSeconds: 5

ingress:
  class: nginx
  endpoint: ffc-tcg-customer-registry
  server: example.com

aadPodIdentity: true

azureIdentity:
  clientID: not-a-real-clientID
  resourceID: not-a-real-resourceID