environment: production
environmentCode:
name: tcg-customer-registry
namespace: tcg-customer
workstream: tcg-customer
image: tcg-customer-registry

labels:
  component: service

appInsights:
  connectionString:

containerConfigMap:
  name: tcg-customer-registry-config-map

containerSecret:
  name: tcg-customer-registry-container-secret
  type: Opaque

deployment: {}

container:
  requestMemory: 100Mi
  requestCpu: 100m
  limitMemory: 100Mi
  limitCpu: 100m
  port: 3053

livenessProbe:
  path: /healthz
  port: 3053
  initialDelaySeconds: 20
  periodSeconds: 10
  failureThreshold: 3
  timeoutSeconds: 5

readinessProbe:
  path: /healthy
  port: 3053
  initialDelaySeconds: 30
  periodSeconds: 10
  failureThreshold: 3
  timeoutSeconds: 5
